apiVersion: apps/v1
kind: Deployment
metadata:
  # name: mathfront-api
  name: redis
spec:
  replicas: 1 #3
  selector:
    matchLabels:
      app: redis # mathfront
  template:
    metadata:
      labels:
        app: redis #mathfront
    spec:
      containers:
      - name: redis # api
        image: sowola/redis:latest
        ports:
        - containerPort: 6379 # 5000
