FROM python:3.9-slim

WORKDIR /app

COPY mainFiles/ ./mainFiles/
COPY instance/ ./instance/
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 500

CMD ["python", "mainFiles/api.py"]