apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 2  # Можно увеличить количество реплик для масштабирования
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: your-worker-image  # Заменить на имя вашего образа для worker
        command: ["celery", "-A", "tasks", "worker", "--loglevel=info"]  # Запуск Celery worker
        env:
        - name: REDIS_URL
          value: "redis://redis:6379/0"  # URL для подключения к Redis
        ports:
        - containerPort: 5555  # Порт для Celery Flower
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: worker
spec:
  selector:
    app: worker
  ports:
    - protocol: TCP
      port: 5555  # Порт для Celery Flower
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - port: 6379
  selector:
    app: redis